name: KillReward
version: '${project.version}'
main: yule.activity.killreward.KillReward
api-version: 1.18
authors: [ Yeqi ]
softdepend:
  - MythicMobs
  - YeqiLib
  - PlaceholderAPI
commands:
  killreward:
    aliases:
      - kr
      - kreward